Repository inception-project/inception-external-recommender, pull requests merged in 2024-03, with the labels that each got.

#55 Add FlairNLP Sequence Tagging
  README.md
  ariadne/contrib/flair.py
  setup.py
Labels: enhancement

#57 #56 - Add simple logging recommender for testing
  ariadne/contrib/log_only.py
Labels: ⭐️ Enhancement

#59 #58 - Recommender only ever trained once
  ariadne/server.py
Labels: 🐛Bug

#61 #60 - Make label an optional parameter when creating a prediction
  ariadne/contrib/inception_util.py
Labels: ⭐️ Enhancement
